# pushgateway:
#   endpoint: https://httpbin.org/put
# ALTERNATIVE: export PFE_PUSHGATEWAY_ENDPOINT="https://httpbin.org/put"

feeds:
  openssl-announce:
    uri: https://www.mail-archive.com/openssl-announce@openssl.org/maillist.xml
    excludes:
      - 'published < now - duration("720h")'
    includes:
      - 'title.contains("Security")'

  helm-releases:
    uri: https://github.com/helm/helm/releases.atom
    entry_id: 'links[0]'
    headers:
      Authorization: "Bearer ${GITHUB_API_TOKEN}"
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      - 'content.contains("is a security")'

  aws-security:
    uri: https://aws.amazon.com/security/security-bulletins/rss/feed/
    entry_id: 'links[0]'
    excludes:
      - 'published < now - duration("720h")'

  grafana:
    uri: https://grafana.com/tags/security/index.xml
    entry_id: 'links[0]'
    excludes:
      - 'published < now - duration("720h")'
    includes:
      - 'title.contains("Grafana security")'
      - 'title.contains("CVE-")'

  gitlab:
    uri: https://about.gitlab.com/security-releases.xml
    entry_id: 'links[0]'
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      - 'content.contains("High") || content.contains("Critical") '

  docker-security:
    uri: https://www.docker.com/blog/tag/security/feed/
    headers:
      user-agent: curl/8.0.1
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      - 'title.contains("Security Advisory")'

  aqua-security:
    uri: https://www.aquasec.com/tag/security-threats/feed/
    headers:
      user-agent: curl/8.0.1
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      - 'title.contains("CVE")'

  istio-security:
    uri: https://istio.io/latest/news/feed.xml
    excludes:
      - 'published < now - duration("720h")'
    includes:
      - 'title.contains("ISTIO-SECURITY")'

  kubernetes:
    uri: https://kubernetes.io/docs/reference/issues-security/official-cve-feed/feed.xml
    entry_id: 'links[0]'
    excludes:
      - 'published < now - duration("720h")'

  kyverno:
    uri: https://kyverno.io/blog/index.xml
    entry_id: 'links[0]'
    excludes:
      - 'published < now - duration("720h")'
    includes:
      - 'title.contains("CVE-")'
      - 'content.contains("CVE-")'

  vault-releases:
    uri: https://github.com/hashicorp/vault/releases.atom
    entry_id: 'links[0]'
    excludes:
      - 'updated < now - duration("720h")'
      - '!title.matches("^v[0-9]+.[0-9]+.[0-9]+(\\+.*)?$")' # only stable releases
    includes:
      - 'content.contains("SECURITY")'

  connaisseur-releases:
    uri: https://github.com/sse-secure-systems/connaisseur/releases.atom
    entry_id: 'links[0]'
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      # they seem to use conventional commits with "sec" as identifier
      # https://github.com/sse-secure-systems/connaisseur/commit/524b73ff7306707f6d3a4d1e86401479bca91b02
      - 'content.contains("Sec")'

  prometheus-alertmanager:
    uri: https://github.com/prometheus/alertmanager/releases.atom
    entry_id: 'links[0]'
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      - 'content.contains("[SECURITY]")'
      - 'content.contains("CVE-")'

  prometheus:
    uri: https://github.com/prometheus/prometheus/releases.atom
    entry_id: 'links[0]'
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      - 'content.contains("[SECURITY]")'
      - 'content.contains("CVE-")'

  prometheus-nodeexporter:
    uri: https://github.com/prometheus/node_exporter/releases.atom
    entry_id: 'links[0]'
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      - 'content.contains("[SECURITY]")'
      - 'content.contains("CVE-")'

  prometheus-pushgateway:
    uri: https://github.com/prometheus/pushgateway/releases.atom
    entry_id: 'links[0]'
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      - 'content.contains("[SECURITY]")'
      - 'content.contains("CVE-")'

  prometheus-blackboxexporter:
    uri: https://github.com/prometheus/blackbox_exporter/releases.atom
    entry_id: 'links[0]'
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      - 'content.contains("[SECURITY]")'
      - 'content.contains("CVE-")'

  oauth2-proxy:
    uri: https://github.com/oauth2-proxy/oauth2-proxy/releases.atom
    entry_id: 'links[0]'
    excludes:
      - 'updated < now - duration("720h")'
    includes:
      # they don't seem to have a common format, so just match as much as possible
      - 'content.contains("security") || content.contains("Security")'
      - 'content.contains("CVE")'
      - 'content.contains("GHSA")'
      - 'content.contains("vulnerabilities") || content.contains("Vulnerablities")'
