name: build

on:
  push:
    branches:
      - main
      
env:
  CARGO_TERM_COLOR: always
  RUST_MIN_STACK: 16777212

permissions: {}

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update

      - uses: swatinem/rust-cache@v2

      - name: Test
        run: |
          cargo test --workspace

      - name: Build
        run: |
          cargo build --release --package prometheus-feed-exporter

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-feed-exporter
          path: target/release/prometheus-feed-exporter
          if-no-files-found: error

      - name: Build (linux-armv7-gnueabihf)
        run: |
          rustup target add armv7-unknown-linux-gnueabihf
          sudo apt-get install -yq gcc-arm-linux-gnueabihf
          export CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=/usr/bin/arm-linux-gnueabihf-gcc
          cargo build --release --package prometheus-feed-exporter --no-default-features --features rustls --target armv7-unknown-linux-gnueabihf

      - name: Upload artifacts (linux-armv7-gnueabihf)
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-feed-exporter-linux-armv7-gnueabihf
          path: target/armv7-unknown-linux-gnueabihf/release/prometheus-feed-exporter
          if-no-files-found: error

      - name: Build (linux-aarch64-gnu)
        run: |
          rustup target add aarch64-unknown-linux-gnu
          sudo apt-get install -yq gcc-aarch64-linux-gnu
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/aarch64-linux-gnu-gcc
          cargo build --release --package prometheus-feed-exporter --no-default-features --features rustls --target aarch64-unknown-linux-gnu

      - name: Upload artifacts (linux-aarch64-gnu)
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-feed-exporter-linux-aarch64-gnu
          path: target/aarch64-unknown-linux-gnu/release/prometheus-feed-exporter
          if-no-files-found: error

      - name: Build (linux-x86_64-musl)
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get install -yq musl-tools
          cargo build --release --package prometheus-feed-exporter --no-default-features --features rustls --target x86_64-unknown-linux-musl

      - name: Upload artifacts (linux-x86_64-musl)
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-feed-exporter-linux-x86_64-musl
          path: target/x86_64-unknown-linux-musl/release/prometheus-feed-exporter
          if-no-files-found: error
