name: build

on:
  push:
    branches:
      - main

env:
  # CARGO_TERM_COLOR: always
  # RUST_MIN_STACK: 16777212
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-docker:
    name: Publish Docker Test Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        target: linux/amd64
        # target: linux/amd64, linux/arm/v7
        push: true
        tags: ${{ env.IMAGE_NAME }}:dev
